// some common spelling mistakes/inconsistencies included so user won't get false negative.
var panda = [
    "mammal",
    "white",
    "black",
    "large",
    "big",
    "sleepy",
    "furry",
    "fluffy",
    "vegetarian",
    "eat bamboo",
    "type of bear",
    "like trees",
    "live in china",
    "live in asia",
    "live in zoo",
    "night",
    "six fingers",
    "cute",
    "like sleep",
    "sleep",
    "sleep a lot",
    "walk",
    "land",
    "multicoloured",
    "multicolored",

];
panda.name = "panda";
var crow = [
    "bird",
    "black",
    "fly",
    "smart",
    "solve problems",
    "problem solver",
    "use tools",
    "community",
    "remember faces",
    "omen",
    "murder",
    "group",
    "intelligent",
    "small",
    "beak",
    "wing",
    "feather",
    "omnivore",
    "land",
    "trees",
    "give gifts",
];
crow.name = "crow";
var parrot = [
    "bird",
    "colourful",
    "red",
    "green",
    "yellow",
    "blue",
    "tropical",
    "beak",
    "multi-colour",
    "colorful",
    "multicolour",
    "multi-color",
    "multicolor",
    "talk",
    "jungle",
    "rain forest",
    "rainforest",
    "fly",
    "omnivore",
    "seeds",
    "feather",
    "speak",
    "white face",
    "land",
    "trees"
];
parrot.name = "parrot";
var blueWhale = [
    "mammal",
    "ocean",
    "aquatic",
    "krill",
    "blue",
    "big",
    "giant",
    "large",
    "whale",
    "carnivore",
    "endangered",
    "old",
    "bumpy",
    "ancient",
    "water",
    "bigger than a house"
];
blueWhale.name = "blue whale";
var elephant = [
    "big",
    "smart",
    "intelligent",
    "grey",
    "mammal",
    "large",
    "giant",
    "trunk",
    "ears",
    "big ears",
    "tusks",
    "ivory",
    "community",
    "family",
    "endangered",
    "africa",
    "asia",
    "herd",
    "never forget",
    "remember",
    "poach",
    "gentle",
    "land",
    "bigger than a car",
    "larger than a car",
];
elephant.name = "elephant";
var anaconda = [
    "reptile",
    "snake",
    "long",
    "thick",
    "squeeze",
    "carnivore",
    "trap",
    "jungle",
    "south america",
    "aquatic",
    "green",
    "yellow",
    "dark",
    "spots",
    "constrict",
    "heavy",
    "shed",
    "scales", 
    "amazon",
    "rainforest",
    "rain forest",
    "land",
    "slither",
    "tongue",
    "fangs",
    "scary"
];
anaconda.name = "anaconda";
var objList = [panda, crow, parrot, blueWhale, elephant, anaconda];
export default objList;